site_name: Inari
site_url: "https://tkamenoko.github.io/inari/"

docs_dir: "markdown"
site_dir: "docs"
repo_url: "https://github.com/tkamenoko/inari/"
edit_uri: ""

theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'red'
  feature:
    tabs: true

markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: True
  - smarty
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink


plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - inari:
      module: inari
      out-name: api
