# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='inari',
    version='0.0.1',
    description='Write docstrings in Markdown!',
    python_requires='>=3.7',
    author='T.Kameyama',
    author_email='tkamenoko@vivaldi.net',
    license='MIT',
    entry_points={
        'console_scripts': ['inari = inari.cli:run'],
        'mkdocs.plugins': ['inari = inari.mkdocs_plugin:Plugin']
    },
    packages=['inari'],
    package_data={},
    install_requires=[],
    extras_require={
        'dev': ['black', 'flake8', 'mypy', 'rope'],
        'docs': ['mkdocs', 'mkdocs-material'],
        'mkdocs': ['mkdocs']
    },
)
